/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.usemoonai.moonsdk.models.TransactionRequest;
import org.usemoonai.moonsdk.models.Tx;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.usemoonai.moonsdk.client.JSON;

/**
 * TransactionData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-17T13:07:28.038327556+10:00[Australia/Brisbane]", comments = "Generator version: 7.4.0")
public class TransactionData {
  public static final String SERIALIZED_NAME_MOON_SCAN_URL = "moon_scan_url";
  @SerializedName(SERIALIZED_NAME_MOON_SCAN_URL)
  private String moonScanUrl;

  public static final String SERIALIZED_NAME_TRANSACTION_HASH = "transaction_hash";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_HASH)
  private String transactionHash;

  public static final String SERIALIZED_NAME_SIGNED_TRANSACTION = "signed_transaction";
  @SerializedName(SERIALIZED_NAME_SIGNED_TRANSACTION)
  private String signedTransaction;

  public static final String SERIALIZED_NAME_SIGNED_MESSAGE = "signed_message";
  @SerializedName(SERIALIZED_NAME_SIGNED_MESSAGE)
  private String signedMessage;

  public static final String SERIALIZED_NAME_RAW_TRANSACTION = "raw_transaction";
  @SerializedName(SERIALIZED_NAME_RAW_TRANSACTION)
  private String rawTransaction;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
  @SerializedName(SERIALIZED_NAME_TRANSACTION)
  private Tx transaction;

  public static final String SERIALIZED_NAME_USER_OPS = "userOps";
  @SerializedName(SERIALIZED_NAME_USER_OPS)
  private List<TransactionRequest> userOps;

  public static final String SERIALIZED_NAME_USEROP_TRANSACTION = "userop_transaction";
  @SerializedName(SERIALIZED_NAME_USEROP_TRANSACTION)
  private String useropTransaction;

  public TransactionData() {
  }

  public TransactionData moonScanUrl(String moonScanUrl) {
    this.moonScanUrl = moonScanUrl;
    return this;
  }

   /**
   * Get moonScanUrl
   * @return moonScanUrl
  **/
  @javax.annotation.Nullable
  public String getMoonScanUrl() {
    return moonScanUrl;
  }

  public void setMoonScanUrl(String moonScanUrl) {
    this.moonScanUrl = moonScanUrl;
  }


  public TransactionData transactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nonnull
  public String getTransactionHash() {
    return transactionHash;
  }

  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public TransactionData signedTransaction(String signedTransaction) {
    this.signedTransaction = signedTransaction;
    return this;
  }

   /**
   * Get signedTransaction
   * @return signedTransaction
  **/
  @javax.annotation.Nonnull
  public String getSignedTransaction() {
    return signedTransaction;
  }

  public void setSignedTransaction(String signedTransaction) {
    this.signedTransaction = signedTransaction;
  }


  public TransactionData signedMessage(String signedMessage) {
    this.signedMessage = signedMessage;
    return this;
  }

   /**
   * Get signedMessage
   * @return signedMessage
  **/
  @javax.annotation.Nullable
  public String getSignedMessage() {
    return signedMessage;
  }

  public void setSignedMessage(String signedMessage) {
    this.signedMessage = signedMessage;
  }


  public TransactionData rawTransaction(String rawTransaction) {
    this.rawTransaction = rawTransaction;
    return this;
  }

   /**
   * Get rawTransaction
   * @return rawTransaction
  **/
  @javax.annotation.Nullable
  public String getRawTransaction() {
    return rawTransaction;
  }

  public void setRawTransaction(String rawTransaction) {
    this.rawTransaction = rawTransaction;
  }


  public TransactionData signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nullable
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }


  public TransactionData transaction(Tx transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @javax.annotation.Nullable
  public Tx getTransaction() {
    return transaction;
  }

  public void setTransaction(Tx transaction) {
    this.transaction = transaction;
  }


  public TransactionData userOps(List<TransactionRequest> userOps) {
    this.userOps = userOps;
    return this;
  }

  public TransactionData addUserOpsItem(TransactionRequest userOpsItem) {
    if (this.userOps == null) {
      this.userOps = new ArrayList<>();
    }
    this.userOps.add(userOpsItem);
    return this;
  }

   /**
   * Get userOps
   * @return userOps
  **/
  @javax.annotation.Nullable
  public List<TransactionRequest> getUserOps() {
    return userOps;
  }

  public void setUserOps(List<TransactionRequest> userOps) {
    this.userOps = userOps;
  }


  public TransactionData useropTransaction(String useropTransaction) {
    this.useropTransaction = useropTransaction;
    return this;
  }

   /**
   * Get useropTransaction
   * @return useropTransaction
  **/
  @javax.annotation.Nullable
  public String getUseropTransaction() {
    return useropTransaction;
  }

  public void setUseropTransaction(String useropTransaction) {
    this.useropTransaction = useropTransaction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionData transactionData = (TransactionData) o;
    return Objects.equals(this.moonScanUrl, transactionData.moonScanUrl) &&
        Objects.equals(this.transactionHash, transactionData.transactionHash) &&
        Objects.equals(this.signedTransaction, transactionData.signedTransaction) &&
        Objects.equals(this.signedMessage, transactionData.signedMessage) &&
        Objects.equals(this.rawTransaction, transactionData.rawTransaction) &&
        Objects.equals(this.signature, transactionData.signature) &&
        Objects.equals(this.transaction, transactionData.transaction) &&
        Objects.equals(this.userOps, transactionData.userOps) &&
        Objects.equals(this.useropTransaction, transactionData.useropTransaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moonScanUrl, transactionHash, signedTransaction, signedMessage, rawTransaction, signature, transaction, userOps, useropTransaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionData {\n");
    sb.append("    moonScanUrl: ").append(toIndentedString(moonScanUrl)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    signedTransaction: ").append(toIndentedString(signedTransaction)).append("\n");
    sb.append("    signedMessage: ").append(toIndentedString(signedMessage)).append("\n");
    sb.append("    rawTransaction: ").append(toIndentedString(rawTransaction)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    userOps: ").append(toIndentedString(userOps)).append("\n");
    sb.append("    useropTransaction: ").append(toIndentedString(useropTransaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("moon_scan_url");
    openapiFields.add("transaction_hash");
    openapiFields.add("signed_transaction");
    openapiFields.add("signed_message");
    openapiFields.add("raw_transaction");
    openapiFields.add("signature");
    openapiFields.add("transaction");
    openapiFields.add("userOps");
    openapiFields.add("userop_transaction");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("transaction_hash");
    openapiRequiredFields.add("signed_transaction");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TransactionData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransactionData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransactionData is not found in the empty JSON string", TransactionData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransactionData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TransactionData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TransactionData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("moon_scan_url") != null && !jsonObj.get("moon_scan_url").isJsonNull()) && !jsonObj.get("moon_scan_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `moon_scan_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("moon_scan_url").toString()));
      }
      if (!jsonObj.get("transaction_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_hash").toString()));
      }
      if (!jsonObj.get("signed_transaction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signed_transaction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signed_transaction").toString()));
      }
      if ((jsonObj.get("signed_message") != null && !jsonObj.get("signed_message").isJsonNull()) && !jsonObj.get("signed_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signed_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signed_message").toString()));
      }
      if ((jsonObj.get("raw_transaction") != null && !jsonObj.get("raw_transaction").isJsonNull()) && !jsonObj.get("raw_transaction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `raw_transaction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("raw_transaction").toString()));
      }
      if ((jsonObj.get("signature") != null && !jsonObj.get("signature").isJsonNull()) && !jsonObj.get("signature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signature").toString()));
      }
      // validate the optional field `transaction`
      if (jsonObj.get("transaction") != null && !jsonObj.get("transaction").isJsonNull()) {
        Tx.validateJsonElement(jsonObj.get("transaction"));
      }
      if (jsonObj.get("userOps") != null && !jsonObj.get("userOps").isJsonNull()) {
        JsonArray jsonArrayuserOps = jsonObj.getAsJsonArray("userOps");
        if (jsonArrayuserOps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("userOps").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `userOps` to be an array in the JSON string but got `%s`", jsonObj.get("userOps").toString()));
          }

          // validate the optional field `userOps` (array)
          for (int i = 0; i < jsonArrayuserOps.size(); i++) {
            TransactionRequest.validateJsonElement(jsonArrayuserOps.get(i));
          };
        }
      }
      if ((jsonObj.get("userop_transaction") != null && !jsonObj.get("userop_transaction").isJsonNull()) && !jsonObj.get("userop_transaction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userop_transaction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userop_transaction").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionData.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionData>() {
           @Override
           public void write(JsonWriter out, TransactionData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TransactionData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TransactionData
  * @throws IOException if the JSON string is invalid with respect to TransactionData
  */
  public static TransactionData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionData.class);
  }

 /**
  * Convert an instance of TransactionData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

