/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.api;

import org.usemoonai.moonsdk.client.ApiException;
import org.usemoonai.moonsdk.models.ConveyorFinanceControllerResponse;
import org.usemoonai.moonsdk.models.TokenSwapParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConveyorFinanceApi
 */
@Disabled
public class ConveyorFinanceApiTest {

    private final ConveyorFinanceApi api = new ConveyorFinanceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void swapTest() throws ApiException {
        String authorization = null;
        String name = null;
        TokenSwapParams tokenSwapParams = null;
        ConveyorFinanceControllerResponse response = api.swap(authorization, name, tokenSwapParams);
        // TODO: test validations
    }

}
