/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.api;

import org.usemoonai.moonsdk.client.ApiException;
import org.usemoonai.moonsdk.models.AccountControllerResponse;
import org.usemoonai.moonsdk.models.Erc1155Request;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Erc1155Api
 */
@Disabled
public class Erc1155ApiTest {

    private final Erc1155Api api = new Erc1155Api();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void balanceOfTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.balanceOf(name, authorization, erc1155Request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void balanceOfBatchTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.balanceOfBatch(name, authorization, erc1155Request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void isApprovedForAllTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.isApprovedForAll(name, authorization, erc1155Request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void safeBatchTransferFromTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.safeBatchTransferFrom(name, authorization, erc1155Request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void safeTransferFromTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.safeTransferFrom(name, authorization, erc1155Request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setApprovalForAllTest() throws ApiException {
        String name = null;
        String authorization = null;
        Erc1155Request erc1155Request = null;
        AccountControllerResponse response = api.setApprovalForAll(name, authorization, erc1155Request);
        // TODO: test validations
    }

}
