/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AaveReservesData
 */
public class AaveReservesDataTest {
    private final AaveReservesData model = new AaveReservesData();

    /**
     * Model tests for AaveReservesData
     */
    @Test
    public void testAaveReservesData() {
        // TODO: test AaveReservesData
    }

    /**
     * Test the property 'currentAtokenBalance'
     */
    @Test
    public void currentAtokenBalanceTest() {
        // TODO: test currentAtokenBalance
    }

    /**
     * Test the property 'currentBorrowBalance'
     */
    @Test
    public void currentBorrowBalanceTest() {
        // TODO: test currentBorrowBalance
    }

    /**
     * Test the property 'principalBorrowBalance'
     */
    @Test
    public void principalBorrowBalanceTest() {
        // TODO: test principalBorrowBalance
    }

    /**
     * Test the property 'borrowRateMode'
     */
    @Test
    public void borrowRateModeTest() {
        // TODO: test borrowRateMode
    }

    /**
     * Test the property 'borrowRate'
     */
    @Test
    public void borrowRateTest() {
        // TODO: test borrowRate
    }

    /**
     * Test the property 'liquidityRate'
     */
    @Test
    public void liquidityRateTest() {
        // TODO: test liquidityRate
    }

    /**
     * Test the property 'originationFee'
     */
    @Test
    public void originationFeeTest() {
        // TODO: test originationFee
    }

    /**
     * Test the property 'variableBorrowIndex'
     */
    @Test
    public void variableBorrowIndexTest() {
        // TODO: test variableBorrowIndex
    }

    /**
     * Test the property 'lastUpdateTimestamp'
     */
    @Test
    public void lastUpdateTimestampTest() {
        // TODO: test lastUpdateTimestamp
    }

    /**
     * Test the property 'usageAsCollateralEnabled'
     */
    @Test
    public void usageAsCollateralEnabledTest() {
        // TODO: test usageAsCollateralEnabled
    }

}
