/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PaymentType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SupportedPaymentTypesMessage
 */
public class SupportedPaymentTypesMessageTest {
    private final SupportedPaymentTypesMessage model = new SupportedPaymentTypesMessage();

    /**
     * Model tests for SupportedPaymentTypesMessage
     */
    @Test
    public void testSupportedPaymentTypesMessage() {
        // TODO: test SupportedPaymentTypesMessage
    }

    /**
     * Test the property 'googlepay'
     */
    @Test
    public void googlepayTest() {
        // TODO: test googlepay
    }

    /**
     * Test the property 'applepay'
     */
    @Test
    public void applepayTest() {
        // TODO: test applepay
    }

    /**
     * Test the property 'creditcard'
     */
    @Test
    public void creditcardTest() {
        // TODO: test creditcard
    }

}
