/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.usemoonai.moonsdk.client.JSON;

/**
 * Erc1155Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-26T19:21:21.691562056+10:00[Australia/Brisbane]")
public class Erc1155Response {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Double type;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chain_id";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  private Double chainId;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private String data;

  public static final String SERIALIZED_NAME_GAS = "gas";
  @SerializedName(SERIALIZED_NAME_GAS)
  private String gas;

  public static final String SERIALIZED_NAME_GAS_PRICE = "gas_price";
  @SerializedName(SERIALIZED_NAME_GAS_PRICE)
  private String gasPrice;

  public static final String SERIALIZED_NAME_GAS_TIP_CAP = "gas_tip_cap";
  @SerializedName(SERIALIZED_NAME_GAS_TIP_CAP)
  private String gasTipCap;

  public static final String SERIALIZED_NAME_GAS_FEE_CAP = "gas_fee_cap";
  @SerializedName(SERIALIZED_NAME_GAS_FEE_CAP)
  private String gasFeeCap;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_NONCE = "nonce";
  @SerializedName(SERIALIZED_NAME_NONCE)
  private Double nonce;

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  private String from;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  public static final String SERIALIZED_NAME_BLOB_GAS = "blob_gas";
  @SerializedName(SERIALIZED_NAME_BLOB_GAS)
  private String blobGas;

  public static final String SERIALIZED_NAME_BLOB_GAS_FEE_CAP = "blob_gas_fee_cap";
  @SerializedName(SERIALIZED_NAME_BLOB_GAS_FEE_CAP)
  private String blobGasFeeCap;

  public static final String SERIALIZED_NAME_BLOB_HASHES = "blob_hashes";
  @SerializedName(SERIALIZED_NAME_BLOB_HASHES)
  private List<String> blobHashes;

  public static final String SERIALIZED_NAME_V = "v";
  @SerializedName(SERIALIZED_NAME_V)
  private String v;

  public static final String SERIALIZED_NAME_R = "r";
  @SerializedName(SERIALIZED_NAME_R)
  private String r;

  public static final String SERIALIZED_NAME_S = "s";
  @SerializedName(SERIALIZED_NAME_S)
  private String s;

  public static final String SERIALIZED_NAME_BALANCE_OF = "balance_of";
  @SerializedName(SERIALIZED_NAME_BALANCE_OF)
  private String balanceOf;

  public static final String SERIALIZED_NAME_BALANCE_OF_BATCH = "balance_of_batch";
  @SerializedName(SERIALIZED_NAME_BALANCE_OF_BATCH)
  private String balanceOfBatch;

  public Erc1155Response() {
  }

  public Erc1155Response type(Double type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  public Double getType() {
    return type;
  }

  public void setType(Double type) {
    this.type = type;
  }


  public Erc1155Response chainId(Double chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @javax.annotation.Nullable
  public Double getChainId() {
    return chainId;
  }

  public void setChainId(Double chainId) {
    this.chainId = chainId;
  }


  public Erc1155Response data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  public Erc1155Response gas(String gas) {
    this.gas = gas;
    return this;
  }

   /**
   * Get gas
   * @return gas
  **/
  @javax.annotation.Nullable
  public String getGas() {
    return gas;
  }

  public void setGas(String gas) {
    this.gas = gas;
  }


  public Erc1155Response gasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
    return this;
  }

   /**
   * Get gasPrice
   * @return gasPrice
  **/
  @javax.annotation.Nullable
  public String getGasPrice() {
    return gasPrice;
  }

  public void setGasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
  }


  public Erc1155Response gasTipCap(String gasTipCap) {
    this.gasTipCap = gasTipCap;
    return this;
  }

   /**
   * Get gasTipCap
   * @return gasTipCap
  **/
  @javax.annotation.Nullable
  public String getGasTipCap() {
    return gasTipCap;
  }

  public void setGasTipCap(String gasTipCap) {
    this.gasTipCap = gasTipCap;
  }


  public Erc1155Response gasFeeCap(String gasFeeCap) {
    this.gasFeeCap = gasFeeCap;
    return this;
  }

   /**
   * Get gasFeeCap
   * @return gasFeeCap
  **/
  @javax.annotation.Nullable
  public String getGasFeeCap() {
    return gasFeeCap;
  }

  public void setGasFeeCap(String gasFeeCap) {
    this.gasFeeCap = gasFeeCap;
  }


  public Erc1155Response value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  public Erc1155Response nonce(Double nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  @javax.annotation.Nullable
  public Double getNonce() {
    return nonce;
  }

  public void setNonce(Double nonce) {
    this.nonce = nonce;
  }


  public Erc1155Response from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @javax.annotation.Nullable
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }


  public Erc1155Response to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }


  public Erc1155Response blobGas(String blobGas) {
    this.blobGas = blobGas;
    return this;
  }

   /**
   * Get blobGas
   * @return blobGas
  **/
  @javax.annotation.Nullable
  public String getBlobGas() {
    return blobGas;
  }

  public void setBlobGas(String blobGas) {
    this.blobGas = blobGas;
  }


  public Erc1155Response blobGasFeeCap(String blobGasFeeCap) {
    this.blobGasFeeCap = blobGasFeeCap;
    return this;
  }

   /**
   * Get blobGasFeeCap
   * @return blobGasFeeCap
  **/
  @javax.annotation.Nullable
  public String getBlobGasFeeCap() {
    return blobGasFeeCap;
  }

  public void setBlobGasFeeCap(String blobGasFeeCap) {
    this.blobGasFeeCap = blobGasFeeCap;
  }


  public Erc1155Response blobHashes(List<String> blobHashes) {
    this.blobHashes = blobHashes;
    return this;
  }

  public Erc1155Response addBlobHashesItem(String blobHashesItem) {
    if (this.blobHashes == null) {
      this.blobHashes = new ArrayList<>();
    }
    this.blobHashes.add(blobHashesItem);
    return this;
  }

   /**
   * Get blobHashes
   * @return blobHashes
  **/
  @javax.annotation.Nullable
  public List<String> getBlobHashes() {
    return blobHashes;
  }

  public void setBlobHashes(List<String> blobHashes) {
    this.blobHashes = blobHashes;
  }


  public Erc1155Response v(String v) {
    this.v = v;
    return this;
  }

   /**
   * Get v
   * @return v
  **/
  @javax.annotation.Nullable
  public String getV() {
    return v;
  }

  public void setV(String v) {
    this.v = v;
  }


  public Erc1155Response r(String r) {
    this.r = r;
    return this;
  }

   /**
   * Get r
   * @return r
  **/
  @javax.annotation.Nullable
  public String getR() {
    return r;
  }

  public void setR(String r) {
    this.r = r;
  }


  public Erc1155Response s(String s) {
    this.s = s;
    return this;
  }

   /**
   * Get s
   * @return s
  **/
  @javax.annotation.Nullable
  public String getS() {
    return s;
  }

  public void setS(String s) {
    this.s = s;
  }


  public Erc1155Response balanceOf(String balanceOf) {
    this.balanceOf = balanceOf;
    return this;
  }

   /**
   * Get balanceOf
   * @return balanceOf
  **/
  @javax.annotation.Nullable
  public String getBalanceOf() {
    return balanceOf;
  }

  public void setBalanceOf(String balanceOf) {
    this.balanceOf = balanceOf;
  }


  public Erc1155Response balanceOfBatch(String balanceOfBatch) {
    this.balanceOfBatch = balanceOfBatch;
    return this;
  }

   /**
   * Get balanceOfBatch
   * @return balanceOfBatch
  **/
  @javax.annotation.Nullable
  public String getBalanceOfBatch() {
    return balanceOfBatch;
  }

  public void setBalanceOfBatch(String balanceOfBatch) {
    this.balanceOfBatch = balanceOfBatch;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Erc1155Response erc1155Response = (Erc1155Response) o;
    return Objects.equals(this.type, erc1155Response.type) &&
        Objects.equals(this.chainId, erc1155Response.chainId) &&
        Objects.equals(this.data, erc1155Response.data) &&
        Objects.equals(this.gas, erc1155Response.gas) &&
        Objects.equals(this.gasPrice, erc1155Response.gasPrice) &&
        Objects.equals(this.gasTipCap, erc1155Response.gasTipCap) &&
        Objects.equals(this.gasFeeCap, erc1155Response.gasFeeCap) &&
        Objects.equals(this.value, erc1155Response.value) &&
        Objects.equals(this.nonce, erc1155Response.nonce) &&
        Objects.equals(this.from, erc1155Response.from) &&
        Objects.equals(this.to, erc1155Response.to) &&
        Objects.equals(this.blobGas, erc1155Response.blobGas) &&
        Objects.equals(this.blobGasFeeCap, erc1155Response.blobGasFeeCap) &&
        Objects.equals(this.blobHashes, erc1155Response.blobHashes) &&
        Objects.equals(this.v, erc1155Response.v) &&
        Objects.equals(this.r, erc1155Response.r) &&
        Objects.equals(this.s, erc1155Response.s) &&
        Objects.equals(this.balanceOf, erc1155Response.balanceOf) &&
        Objects.equals(this.balanceOfBatch, erc1155Response.balanceOfBatch);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, chainId, data, gas, gasPrice, gasTipCap, gasFeeCap, value, nonce, from, to, blobGas, blobGasFeeCap, blobHashes, v, r, s, balanceOf, balanceOfBatch);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Erc1155Response {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    gas: ").append(toIndentedString(gas)).append("\n");
    sb.append("    gasPrice: ").append(toIndentedString(gasPrice)).append("\n");
    sb.append("    gasTipCap: ").append(toIndentedString(gasTipCap)).append("\n");
    sb.append("    gasFeeCap: ").append(toIndentedString(gasFeeCap)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    blobGas: ").append(toIndentedString(blobGas)).append("\n");
    sb.append("    blobGasFeeCap: ").append(toIndentedString(blobGasFeeCap)).append("\n");
    sb.append("    blobHashes: ").append(toIndentedString(blobHashes)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    r: ").append(toIndentedString(r)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("    balanceOf: ").append(toIndentedString(balanceOf)).append("\n");
    sb.append("    balanceOfBatch: ").append(toIndentedString(balanceOfBatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("chain_id");
    openapiFields.add("data");
    openapiFields.add("gas");
    openapiFields.add("gas_price");
    openapiFields.add("gas_tip_cap");
    openapiFields.add("gas_fee_cap");
    openapiFields.add("value");
    openapiFields.add("nonce");
    openapiFields.add("from");
    openapiFields.add("to");
    openapiFields.add("blob_gas");
    openapiFields.add("blob_gas_fee_cap");
    openapiFields.add("blob_hashes");
    openapiFields.add("v");
    openapiFields.add("r");
    openapiFields.add("s");
    openapiFields.add("balance_of");
    openapiFields.add("balance_of_batch");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Erc1155Response
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Erc1155Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Erc1155Response is not found in the empty JSON string", Erc1155Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Erc1155Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Erc1155Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) && !jsonObj.get("data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }
      if ((jsonObj.get("gas") != null && !jsonObj.get("gas").isJsonNull()) && !jsonObj.get("gas").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gas` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas").toString()));
      }
      if ((jsonObj.get("gas_price") != null && !jsonObj.get("gas_price").isJsonNull()) && !jsonObj.get("gas_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gas_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas_price").toString()));
      }
      if ((jsonObj.get("gas_tip_cap") != null && !jsonObj.get("gas_tip_cap").isJsonNull()) && !jsonObj.get("gas_tip_cap").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gas_tip_cap` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas_tip_cap").toString()));
      }
      if ((jsonObj.get("gas_fee_cap") != null && !jsonObj.get("gas_fee_cap").isJsonNull()) && !jsonObj.get("gas_fee_cap").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gas_fee_cap` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas_fee_cap").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("from") != null && !jsonObj.get("from").isJsonNull()) && !jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if ((jsonObj.get("to") != null && !jsonObj.get("to").isJsonNull()) && !jsonObj.get("to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
      if ((jsonObj.get("blob_gas") != null && !jsonObj.get("blob_gas").isJsonNull()) && !jsonObj.get("blob_gas").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `blob_gas` to be a primitive type in the JSON string but got `%s`", jsonObj.get("blob_gas").toString()));
      }
      if ((jsonObj.get("blob_gas_fee_cap") != null && !jsonObj.get("blob_gas_fee_cap").isJsonNull()) && !jsonObj.get("blob_gas_fee_cap").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `blob_gas_fee_cap` to be a primitive type in the JSON string but got `%s`", jsonObj.get("blob_gas_fee_cap").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("blob_hashes") != null && !jsonObj.get("blob_hashes").isJsonNull() && !jsonObj.get("blob_hashes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `blob_hashes` to be an array in the JSON string but got `%s`", jsonObj.get("blob_hashes").toString()));
      }
      if ((jsonObj.get("v") != null && !jsonObj.get("v").isJsonNull()) && !jsonObj.get("v").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `v` to be a primitive type in the JSON string but got `%s`", jsonObj.get("v").toString()));
      }
      if ((jsonObj.get("r") != null && !jsonObj.get("r").isJsonNull()) && !jsonObj.get("r").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `r` to be a primitive type in the JSON string but got `%s`", jsonObj.get("r").toString()));
      }
      if ((jsonObj.get("s") != null && !jsonObj.get("s").isJsonNull()) && !jsonObj.get("s").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `s` to be a primitive type in the JSON string but got `%s`", jsonObj.get("s").toString()));
      }
      if ((jsonObj.get("balance_of") != null && !jsonObj.get("balance_of").isJsonNull()) && !jsonObj.get("balance_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `balance_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("balance_of").toString()));
      }
      if ((jsonObj.get("balance_of_batch") != null && !jsonObj.get("balance_of_batch").isJsonNull()) && !jsonObj.get("balance_of_batch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `balance_of_batch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("balance_of_batch").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Erc1155Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Erc1155Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Erc1155Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Erc1155Response.class));

       return (TypeAdapter<T>) new TypeAdapter<Erc1155Response>() {
           @Override
           public void write(JsonWriter out, Erc1155Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Erc1155Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Erc1155Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Erc1155Response
  * @throws IOException if the JSON string is invalid with respect to Erc1155Response
  */
  public static Erc1155Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Erc1155Response.class);
  }

 /**
  * Convert an instance of Erc1155Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

