/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.usemoonai.moonsdk.client.JSON;

/**
 * UniswapInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-26T19:21:21.691562056+10:00[Australia/Brisbane]")
public class UniswapInput {
  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private String data;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private String input;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_NONCE = "nonce";
  @SerializedName(SERIALIZED_NAME_NONCE)
  private String nonce;

  public static final String SERIALIZED_NAME_GAS = "gas";
  @SerializedName(SERIALIZED_NAME_GAS)
  private String gas;

  public static final String SERIALIZED_NAME_GAS_PRICE = "gasPrice";
  @SerializedName(SERIALIZED_NAME_GAS_PRICE)
  private String gasPrice;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chain_id";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  private String chainId;

  public static final String SERIALIZED_NAME_ENCODING = "encoding";
  @SerializedName(SERIALIZED_NAME_ENCODING)
  private String encoding;

  public static final String SERIALIZED_NAME_E_O_A = "EOA";
  @SerializedName(SERIALIZED_NAME_E_O_A)
  private Boolean EOA;

  public static final String SERIALIZED_NAME_CONTRACT_ADDRESS = "contract_address";
  @SerializedName(SERIALIZED_NAME_CONTRACT_ADDRESS)
  private String contractAddress;

  public static final String SERIALIZED_NAME_TOKEN_ID = "token_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_TOKEN_IDS = "token_ids";
  @SerializedName(SERIALIZED_NAME_TOKEN_IDS)
  private String tokenIds;

  public static final String SERIALIZED_NAME_APPROVED = "approved";
  @SerializedName(SERIALIZED_NAME_APPROVED)
  private Boolean approved;

  public static final String SERIALIZED_NAME_BROADCAST = "broadcast";
  @SerializedName(SERIALIZED_NAME_BROADCAST)
  private Boolean broadcast;

  public static final String SERIALIZED_NAME_TOKEN_A = "token_a";
  @SerializedName(SERIALIZED_NAME_TOKEN_A)
  private String tokenA;

  public static final String SERIALIZED_NAME_TOKEN_B = "token_b";
  @SerializedName(SERIALIZED_NAME_TOKEN_B)
  private String tokenB;

  public static final String SERIALIZED_NAME_AMOUNT_A = "amount_a";
  @SerializedName(SERIALIZED_NAME_AMOUNT_A)
  private String amountA;

  public static final String SERIALIZED_NAME_AMOUNT_B = "amount_b";
  @SerializedName(SERIALIZED_NAME_AMOUNT_B)
  private String amountB;

  public UniswapInput() {
  }

  public UniswapInput to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }


  public UniswapInput data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  public UniswapInput input(String input) {
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @javax.annotation.Nullable
  public String getInput() {
    return input;
  }

  public void setInput(String input) {
    this.input = input;
  }


  public UniswapInput value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  public UniswapInput nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  @javax.annotation.Nullable
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public UniswapInput gas(String gas) {
    this.gas = gas;
    return this;
  }

   /**
   * Get gas
   * @return gas
  **/
  @javax.annotation.Nullable
  public String getGas() {
    return gas;
  }

  public void setGas(String gas) {
    this.gas = gas;
  }


  public UniswapInput gasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
    return this;
  }

   /**
   * Get gasPrice
   * @return gasPrice
  **/
  @javax.annotation.Nullable
  public String getGasPrice() {
    return gasPrice;
  }

  public void setGasPrice(String gasPrice) {
    this.gasPrice = gasPrice;
  }


  public UniswapInput chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }


  public UniswapInput encoding(String encoding) {
    this.encoding = encoding;
    return this;
  }

   /**
   * Get encoding
   * @return encoding
  **/
  @javax.annotation.Nullable
  public String getEncoding() {
    return encoding;
  }

  public void setEncoding(String encoding) {
    this.encoding = encoding;
  }


  public UniswapInput EOA(Boolean EOA) {
    this.EOA = EOA;
    return this;
  }

   /**
   * Get EOA
   * @return EOA
  **/
  @javax.annotation.Nullable
  public Boolean getEOA() {
    return EOA;
  }

  public void setEOA(Boolean EOA) {
    this.EOA = EOA;
  }


  public UniswapInput contractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

   /**
   * Get contractAddress
   * @return contractAddress
  **/
  @javax.annotation.Nullable
  public String getContractAddress() {
    return contractAddress;
  }

  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }


  public UniswapInput tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public UniswapInput tokenIds(String tokenIds) {
    this.tokenIds = tokenIds;
    return this;
  }

   /**
   * Get tokenIds
   * @return tokenIds
  **/
  @javax.annotation.Nullable
  public String getTokenIds() {
    return tokenIds;
  }

  public void setTokenIds(String tokenIds) {
    this.tokenIds = tokenIds;
  }


  public UniswapInput approved(Boolean approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  @javax.annotation.Nullable
  public Boolean getApproved() {
    return approved;
  }

  public void setApproved(Boolean approved) {
    this.approved = approved;
  }


  public UniswapInput broadcast(Boolean broadcast) {
    this.broadcast = broadcast;
    return this;
  }

   /**
   * Get broadcast
   * @return broadcast
  **/
  @javax.annotation.Nullable
  public Boolean getBroadcast() {
    return broadcast;
  }

  public void setBroadcast(Boolean broadcast) {
    this.broadcast = broadcast;
  }


  public UniswapInput tokenA(String tokenA) {
    this.tokenA = tokenA;
    return this;
  }

   /**
   * Get tokenA
   * @return tokenA
  **/
  @javax.annotation.Nullable
  public String getTokenA() {
    return tokenA;
  }

  public void setTokenA(String tokenA) {
    this.tokenA = tokenA;
  }


  public UniswapInput tokenB(String tokenB) {
    this.tokenB = tokenB;
    return this;
  }

   /**
   * Get tokenB
   * @return tokenB
  **/
  @javax.annotation.Nullable
  public String getTokenB() {
    return tokenB;
  }

  public void setTokenB(String tokenB) {
    this.tokenB = tokenB;
  }


  public UniswapInput amountA(String amountA) {
    this.amountA = amountA;
    return this;
  }

   /**
   * Get amountA
   * @return amountA
  **/
  @javax.annotation.Nullable
  public String getAmountA() {
    return amountA;
  }

  public void setAmountA(String amountA) {
    this.amountA = amountA;
  }


  public UniswapInput amountB(String amountB) {
    this.amountB = amountB;
    return this;
  }

   /**
   * Get amountB
   * @return amountB
  **/
  @javax.annotation.Nullable
  public String getAmountB() {
    return amountB;
  }

  public void setAmountB(String amountB) {
    this.amountB = amountB;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UniswapInput uniswapInput = (UniswapInput) o;
    return Objects.equals(this.to, uniswapInput.to) &&
        Objects.equals(this.data, uniswapInput.data) &&
        Objects.equals(this.input, uniswapInput.input) &&
        Objects.equals(this.value, uniswapInput.value) &&
        Objects.equals(this.nonce, uniswapInput.nonce) &&
        Objects.equals(this.gas, uniswapInput.gas) &&
        Objects.equals(this.gasPrice, uniswapInput.gasPrice) &&
        Objects.equals(this.chainId, uniswapInput.chainId) &&
        Objects.equals(this.encoding, uniswapInput.encoding) &&
        Objects.equals(this.EOA, uniswapInput.EOA) &&
        Objects.equals(this.contractAddress, uniswapInput.contractAddress) &&
        Objects.equals(this.tokenId, uniswapInput.tokenId) &&
        Objects.equals(this.tokenIds, uniswapInput.tokenIds) &&
        Objects.equals(this.approved, uniswapInput.approved) &&
        Objects.equals(this.broadcast, uniswapInput.broadcast) &&
        Objects.equals(this.tokenA, uniswapInput.tokenA) &&
        Objects.equals(this.tokenB, uniswapInput.tokenB) &&
        Objects.equals(this.amountA, uniswapInput.amountA) &&
        Objects.equals(this.amountB, uniswapInput.amountB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, data, input, value, nonce, gas, gasPrice, chainId, encoding, EOA, contractAddress, tokenId, tokenIds, approved, broadcast, tokenA, tokenB, amountA, amountB);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UniswapInput {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    gas: ").append(toIndentedString(gas)).append("\n");
    sb.append("    gasPrice: ").append(toIndentedString(gasPrice)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    EOA: ").append(toIndentedString(EOA)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    tokenIds: ").append(toIndentedString(tokenIds)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    broadcast: ").append(toIndentedString(broadcast)).append("\n");
    sb.append("    tokenA: ").append(toIndentedString(tokenA)).append("\n");
    sb.append("    tokenB: ").append(toIndentedString(tokenB)).append("\n");
    sb.append("    amountA: ").append(toIndentedString(amountA)).append("\n");
    sb.append("    amountB: ").append(toIndentedString(amountB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("to");
    openapiFields.add("data");
    openapiFields.add("input");
    openapiFields.add("value");
    openapiFields.add("nonce");
    openapiFields.add("gas");
    openapiFields.add("gasPrice");
    openapiFields.add("chain_id");
    openapiFields.add("encoding");
    openapiFields.add("EOA");
    openapiFields.add("contract_address");
    openapiFields.add("token_id");
    openapiFields.add("token_ids");
    openapiFields.add("approved");
    openapiFields.add("broadcast");
    openapiFields.add("token_a");
    openapiFields.add("token_b");
    openapiFields.add("amount_a");
    openapiFields.add("amount_b");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UniswapInput
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UniswapInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UniswapInput is not found in the empty JSON string", UniswapInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UniswapInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UniswapInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("to") != null && !jsonObj.get("to").isJsonNull()) && !jsonObj.get("to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
      if ((jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) && !jsonObj.get("data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }
      if ((jsonObj.get("input") != null && !jsonObj.get("input").isJsonNull()) && !jsonObj.get("input").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `input` to be a primitive type in the JSON string but got `%s`", jsonObj.get("input").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("nonce") != null && !jsonObj.get("nonce").isJsonNull()) && !jsonObj.get("nonce").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nonce` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nonce").toString()));
      }
      if ((jsonObj.get("gas") != null && !jsonObj.get("gas").isJsonNull()) && !jsonObj.get("gas").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gas` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas").toString()));
      }
      if ((jsonObj.get("gasPrice") != null && !jsonObj.get("gasPrice").isJsonNull()) && !jsonObj.get("gasPrice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gasPrice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gasPrice").toString()));
      }
      if ((jsonObj.get("chain_id") != null && !jsonObj.get("chain_id").isJsonNull()) && !jsonObj.get("chain_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chain_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chain_id").toString()));
      }
      if ((jsonObj.get("encoding") != null && !jsonObj.get("encoding").isJsonNull()) && !jsonObj.get("encoding").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `encoding` to be a primitive type in the JSON string but got `%s`", jsonObj.get("encoding").toString()));
      }
      if ((jsonObj.get("contract_address") != null && !jsonObj.get("contract_address").isJsonNull()) && !jsonObj.get("contract_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contract_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contract_address").toString()));
      }
      if ((jsonObj.get("token_id") != null && !jsonObj.get("token_id").isJsonNull()) && !jsonObj.get("token_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_id").toString()));
      }
      if ((jsonObj.get("token_ids") != null && !jsonObj.get("token_ids").isJsonNull()) && !jsonObj.get("token_ids").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_ids` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_ids").toString()));
      }
      if ((jsonObj.get("token_a") != null && !jsonObj.get("token_a").isJsonNull()) && !jsonObj.get("token_a").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_a` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_a").toString()));
      }
      if ((jsonObj.get("token_b") != null && !jsonObj.get("token_b").isJsonNull()) && !jsonObj.get("token_b").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_b` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_b").toString()));
      }
      if ((jsonObj.get("amount_a") != null && !jsonObj.get("amount_a").isJsonNull()) && !jsonObj.get("amount_a").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount_a` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_a").toString()));
      }
      if ((jsonObj.get("amount_b") != null && !jsonObj.get("amount_b").isJsonNull()) && !jsonObj.get("amount_b").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount_b` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_b").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UniswapInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UniswapInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UniswapInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UniswapInput.class));

       return (TypeAdapter<T>) new TypeAdapter<UniswapInput>() {
           @Override
           public void write(JsonWriter out, UniswapInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UniswapInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UniswapInput given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UniswapInput
  * @throws IOException if the JSON string is invalid with respect to UniswapInput
  */
  public static UniswapInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UniswapInput.class);
  }

 /**
  * Convert an instance of UniswapInput to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

