/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionInputSupportedParamsTheme
 */
public class TransactionInputSupportedParamsThemeTest {
    private final TransactionInputSupportedParamsTheme model = new TransactionInputSupportedParamsTheme();

    /**
     * Model tests for TransactionInputSupportedParamsTheme
     */
    @Test
    public void testTransactionInputSupportedParamsTheme() {
        // TODO: test TransactionInputSupportedParamsTheme
    }

    /**
     * Test the property 'borderRadius'
     */
    @Test
    public void borderRadiusTest() {
        // TODO: test borderRadius
    }

    /**
     * Test the property 'cardColor'
     */
    @Test
    public void cardColorTest() {
        // TODO: test cardColor
    }

    /**
     * Test the property 'secondaryTextColor'
     */
    @Test
    public void secondaryTextColorTest() {
        // TODO: test secondaryTextColor
    }

    /**
     * Test the property 'primaryTextColor'
     */
    @Test
    public void primaryTextColorTest() {
        // TODO: test primaryTextColor
    }

    /**
     * Test the property 'secondaryColor'
     */
    @Test
    public void secondaryColorTest() {
        // TODO: test secondaryColor
    }

    /**
     * Test the property 'primaryColor'
     */
    @Test
    public void primaryColorTest() {
        // TODO: test primaryColor
    }

    /**
     * Test the property 'themeName'
     */
    @Test
    public void themeNameTest() {
        // TODO: test themeName
    }

    /**
     * Test the property 'isDark'
     */
    @Test
    public void isDarkTest() {
        // TODO: test isDark
    }

}
