/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TronTransactionOutput
 */
public class TronTransactionOutputTest {
    private final TronTransactionOutput model = new TronTransactionOutput();

    /**
     * Model tests for TronTransactionOutput
     */
    @Test
    public void testTronTransactionOutput() {
        // TODO: test TronTransactionOutput
    }

    /**
     * Test the property 'signedTx'
     */
    @Test
    public void signedTxTest() {
        // TODO: test signedTx
    }

    /**
     * Test the property 'transactionHash'
     */
    @Test
    public void transactionHashTest() {
        // TODO: test transactionHash
    }

}
