/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.usemoonai.moonsdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.usemoonai.moonsdk.models.TriggerOutput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IERC20Transfer
 */
public class IERC20TransferTest {
    private final IERC20Transfer model = new IERC20Transfer();

    /**
     * Model tests for IERC20Transfer
     */
    @Test
    public void testIERC20Transfer() {
        // TODO: test IERC20Transfer
    }

    /**
     * Test the property 'transactionHash'
     */
    @Test
    public void transactionHashTest() {
        // TODO: test transactionHash
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'logIndex'
     */
    @Test
    public void logIndexTest() {
        // TODO: test logIndex
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'tokenDecimals'
     */
    @Test
    public void tokenDecimalsTest() {
        // TODO: test tokenDecimals
    }

    /**
     * Test the property 'tokenName'
     */
    @Test
    public void tokenNameTest() {
        // TODO: test tokenName
    }

    /**
     * Test the property 'tokenSymbol'
     */
    @Test
    public void tokenSymbolTest() {
        // TODO: test tokenSymbol
    }

    /**
     * Test the property 'valueWithDecimals'
     */
    @Test
    public void valueWithDecimalsTest() {
        // TODO: test valueWithDecimals
    }

    /**
     * Test the property 'triggers'
     */
    @Test
    public void triggersTest() {
        // TODO: test triggers
    }

}
