/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccountControllerResponse;
import org.openapitools.client.model.BroadcastInput;
import org.openapitools.client.model.CreateAccountInput;
import org.openapitools.client.model.DeployInput;
import org.openapitools.client.model.InputBody;
import org.openapitools.client.model.SignMessage;
import org.openapitools.client.model.SignTypedData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void broadcastTxTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        BroadcastInput broadcastInput = null;
        AccountControllerResponse response = api.broadcastTx(authorization, accountName, broadcastInput);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAccountTest() throws ApiException {
        String authorization = null;
        CreateAccountInput createAccountInput = null;
        AccountControllerResponse response = api.createAccount(authorization, createAccountInput);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAccountTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        AccountControllerResponse response = api.deleteAccount(authorization, accountName);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deployContractTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        DeployInput deployInput = null;
        AccountControllerResponse response = api.deployContract(authorization, accountName, deployInput);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        AccountControllerResponse response = api.getAccount(authorization, accountName);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBalanceTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        String chainId = null;
        AccountControllerResponse response = api.getBalance(accountName, authorization, chainId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNonceTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        AccountControllerResponse response = api.getNonce(accountName, authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAccountsTest() throws ApiException {
        String authorization = null;
        AccountControllerResponse response = api.listAccounts(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void signMessageTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        SignMessage signMessage = null;
        AccountControllerResponse response = api.signMessage(accountName, authorization, signMessage);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void signTransactionTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        InputBody inputBody = null;
        AccountControllerResponse response = api.signTransaction(accountName, authorization, inputBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void signTypedDataTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        SignTypedData signTypedData = null;
        AccountControllerResponse response = api.signTypedData(accountName, authorization, signTypedData);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferEthTest() throws ApiException {
        String accountName = null;
        String authorization = null;
        InputBody inputBody = null;
        AccountControllerResponse response = api.transferEth(accountName, authorization, inputBody);
        // TODO: test validations
    }

}
