/*
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccountControllerResponse;
import org.openapitools.client.model.InputBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Erc4337Api
 */
@Disabled
public class Erc4337ApiTest {

    private final Erc4337Api api = new Erc4337Api();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAddressTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        InputBody inputBody = null;
        AccountControllerResponse response = api.getAddress(authorization, accountName, inputBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void signBroadcastUserOpTxTest() throws ApiException {
        String authorization = null;
        String accountName = null;
        InputBody inputBody = null;
        AccountControllerResponse response = api.signBroadcastUserOpTx(authorization, accountName, inputBody);
        // TODO: test validations
    }

}
